---
name: Script CI

# CI for scripts used to manage/clean-up acronyms file
# Triggers the workflow on pull request
# events but only on PRs for the master branch
on:
  pull_request:
    paths-ignore:
      - 'acronyms.csv'
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version' # Read python version from a file
      - name: Set up poetry
        uses: abatilo/actions-poetry@v3
      - name: Run tests
        run: make test
